<?php

/**
 * @file
 * Install, update and uninstall functions for the Slack module.
 */

/**
 * Implements hook_uninstall().
 */
function slack_uninstall() {
  variable_del('slack_webhook_url');
  variable_del('slack_channel');
  variable_del('slack_username');
  variable_del('slack_icon_url');
  variable_del('slack_icon_emoji');
  variable_del('slack_icon_type');
  variable_del('slack_enabled_attachment');
  variable_del('slack_attachment_pretext');
  variable_del('slack_attachment_color');
  variable_del('slack_attachment_title');
  variable_del('slack_attachment_title_link');
  variable_del('slack_attachment_image_url');
  variable_del('slack_attachment_author_name');
  variable_del('slack_attachment_author_link');
  variable_del('slack_attachment_author_icon');
  variable_del('slack_attachment_footer');
  variable_del('slack_attachment_footer_icon');
  variable_del('slack_attachment_ts');
  variable_del('slack_attachment_mrkdwn');
  variable_del('slack_token');
  variable_del('slack_file_types');
  variable_del('slack_files_age_number');
  variable_del('slack_files_age_unit');
}
